import {
  resolveOrganizationMember,
  resolveOrganizationMembers,
} from "@/lib/organization/resolve-organization-member";
import type {
  OrganizationMember,
  OrganizationMemberDisplay,
} from "@/lib/organization/types";

export const mockOrganizationMembers: OrganizationMember[] = [
  {
    id: "ca-2026-ex-1",
    personId: "person-hung",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Trưởng ca đoàn",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "ca-2026-ex-2",
    personId: "person-hoa",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Phó trưởng ca đoàn",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "ca-2026-ex-3",
    personId: "person-nam",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Thư ký",
    isExecutive: true,
    sortOrder: 3,
  },
  {
    id: "ca-2026-m-1",
    personId: "person-mai",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Soprano",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "ca-2026-m-2",
    personId: "person-duc",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Tenor",
    isExecutive: false,
    sortOrder: 11,
  },
  {
    id: "ca-2026-m-3",
    personId: "person-tuan",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Bass",
    isExecutive: false,
    sortOrder: 12,
  },
  {
    id: "ca-2020-ex-1",
    personId: "person-son",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Trưởng ca đoàn",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "ca-2020-ex-2",
    personId: "person-lan",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Phó trưởng ca đoàn",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "ca-2020-m-1",
    personId: "person-ngoc",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Ca viên Alto",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "gl-2026-ex-1",
    personId: "person-anh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Trưởng ban",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "gl-2026-ex-2",
    personId: "person-huong",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Phó trưởng ban",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "gl-2026-m-1",
    personId: "person-hanh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Giáo lý viên Chiên Con",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "gl-2026-m-2",
    personId: "person-binh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Giáo lý viên Thiếu niên",
    isExecutive: false,
    sortOrder: 11,
  },
  {
    id: "gl-2020-ex-1",
    personId: "person-phucduc",
    organizationSlug: "ban-giao-ly",
    termId: "2020-2023",
    position: "Trưởng ban",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "gl-2020-m-1",
    personId: "person-loan",
    organizationSlug: "ban-giao-ly",
    termId: "2020-2023",
    position: "Giáo lý viên",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "gd-2026-ex-1",
    personId: "person-thanh",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Chủ tịch",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "gd-2026-ex-2",
    personId: "person-nga",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Phó chủ tịch",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "gd-2026-m-1",
    personId: "person-cuong",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Thành viên Giáo họ Trị Tin",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "gd-2026-m-2",
    personId: "person-thu",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Thành viên Giáo họ Kim Lâm",
    isExecutive: false,
    sortOrder: 11,
  },
  {
    id: "tn-2026-ex-1",
    personId: "person-maingd",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Tổng phụ trách",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "tn-2026-ex-2",
    personId: "person-huy",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Phó phụ trách",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "tn-2026-m-1",
    personId: "person-khoi",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Huynh trưởng",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "tn-2026-m-2",
    personId: "person-an",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Huynh trưởng",
    isExecutive: false,
    sortOrder: 11,
  },
  {
    id: "lm-2026-ex-1",
    personId: "person-hong",
    organizationSlug: "legio-mariae",
    termId: "2023-2026",
    position: "Tổng phụ trách",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "lm-2026-m-1",
    personId: "person-bich",
    organizationSlug: "legio-mariae",
    termId: "2023-2026",
    position: "Thành viên",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "lm-2020-ex-1",
    personId: "person-sen",
    organizationSlug: "legio-mariae",
    termId: "2020-2023",
    position: "Tổng phụ trách",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "hm-2026-ex-1",
    personId: "person-xuan",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Chủ tịch",
    isExecutive: true,
    sortOrder: 1,
  },
  {
    id: "hm-2026-ex-2",
    personId: "person-loanhm",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Phó chủ tịch",
    isExecutive: true,
    sortOrder: 2,
  },
  {
    id: "hm-2026-m-1",
    personId: "person-van",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Thành viên",
    isExecutive: false,
    sortOrder: 10,
  },
  {
    id: "hm-2026-m-2",
    personId: "person-hanhhm",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Thành viên",
    isExecutive: false,
    sortOrder: 11,
  },
];

function sortMembers(list: OrganizationMember[]): OrganizationMember[] {
  return [...list].sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getOrganizationMembersBySlug(
  organizationSlug: string,
): OrganizationMemberDisplay[] {
  return resolveOrganizationMembers(
    sortMembers(
      mockOrganizationMembers.filter(
        (m) => m.organizationSlug === organizationSlug,
      ),
    ),
  );
}

export function getOrganizationMemberById(
  memberId: string,
): OrganizationMemberDisplay | undefined {
  const member = mockOrganizationMembers.find((m) => m.id === memberId);
  return member ? resolveOrganizationMember(member) : undefined;
}
