import type { MemberPerson } from "@/lib/organization/types";

export const mockMemberPersons: MemberPerson[] = [
  {
    id: "person-hung",
    saintName: "Gioan Baotixita",
    realName: "Nguyễn Văn Hùng",
    dateOfBirth: "1975-06-24",
    address: "Khu Đông",
  },
  {
    id: "person-hoa",
    saintName: "Maria",
    realName: "Trần Thị Hoa",
    dateOfBirth: "1982-09-08",
    address: "Khu Tây",
  },
  {
    id: "person-nam",
    saintName: "Phêrô",
    realName: "Lê Hoàng Nam",
    dateOfBirth: "1990-06-29",
    address: "Khu Nam",
  },
  {
    id: "person-mai",
    saintName: "Têrêsa",
    realName: "Phạm Thị Mai",
    dateOfBirth: "1988-10-15",
    address: "Khu Bắc",
  },
  {
    id: "person-duc",
    saintName: "Phanxicô",
    realName: "Hoàng Văn Đức",
    dateOfBirth: "1992-10-04",
    address: "Khu Đông",
  },
  {
    id: "person-tuan",
    saintName: "Giuse",
    realName: "Vũ Minh Tuấn",
    dateOfBirth: "1985-03-19",
    address: "Khu Trung",
  },
  {
    id: "person-son",
    saintName: "Phêrô",
    realName: "Đặng Văn Sơn",
    dateOfBirth: "1968-06-29",
    address: "Khu Tây",
  },
  {
    id: "person-lan",
    saintName: "Anna",
    realName: "Nguyễn Thị Lan",
    dateOfBirth: "1976-07-26",
    address: "Khu Nam",
  },
  {
    id: "person-ngoc",
    saintName: "Cecilia",
    realName: "Lý Thị Ngọc",
    dateOfBirth: "1995-11-22",
    address: "Khu Bắc",
  },
  {
    id: "person-anh",
    saintName: "Phanxicô Xaviê",
    realName: "Lê Văn Anh",
    dateOfBirth: "1991-12-03",
    address: "Khu Kim Lâm",
  },
  {
    id: "person-huong",
    saintName: "Maria",
    realName: "Đinh Thị Hương",
    dateOfBirth: "1987-08-15",
    address: "Khu Trị Tin",
  },
  {
    id: "person-hanh",
    saintName: "Têrêsa",
    realName: "Trần Thị Hạnh",
    dateOfBirth: "1993-10-01",
    address: "Khu Đông",
  },
  {
    id: "person-binh",
    saintName: "Gioan",
    realName: "Phạm Văn Bình",
    dateOfBirth: "1994-06-24",
    address: "Khu Tây",
  },
  {
    id: "person-phucduc",
    saintName: "Giuse",
    realName: "Phạm Minh Đức",
    dateOfBirth: "1970-03-19",
    address: "Khu Nam",
  },
  {
    id: "person-loan",
    saintName: "Anna",
    realName: "Võ Thị Loan",
    dateOfBirth: "1980-07-26",
    address: "Khu Bắc",
  },
  {
    id: "person-thanh",
    saintName: "Giuse",
    realName: "Nguyễn Văn Thành",
    dateOfBirth: "1969-03-19",
    address: "Khu Trung",
  },
  {
    id: "person-nga",
    saintName: "Maria",
    realName: "Trần Thị Nga",
    dateOfBirth: "1974-09-12",
    address: "Khu Đông",
  },
  {
    id: "person-cuong",
    saintName: "Phêrô",
    realName: "Lê Văn Cường",
    dateOfBirth: "1983-04-29",
    address: "Khu Trị Tin",
  },
  {
    id: "person-thu",
    saintName: "Têrêsa",
    realName: "Hoàng Thị Thu",
    dateOfBirth: "1990-10-05",
    address: "Khu Kim Lâm",
  },
  {
    id: "person-maingd",
    saintName: "Maria",
    realName: "Nguyễn Thị Mai",
    dateOfBirth: "1986-09-15",
    address: "Khu Nam",
  },
  {
    id: "person-huy",
    saintName: "Phanxicô",
    realName: "Trần Quốc Huy",
    dateOfBirth: "1992-04-02",
    address: "Khu Tây",
  },
  {
    id: "person-khoi",
    saintName: "Gioan",
    realName: "Lê Minh Khôi",
    dateOfBirth: "1996-06-24",
    address: "Khu Bắc",
  },
  {
    id: "person-an",
    saintName: "Têrêsa",
    realName: "Phạm Ngọc An",
    dateOfBirth: "1997-10-01",
    address: "Khu Đông",
  },
  {
    id: "person-hong",
    saintName: "Maria",
    realName: "Trần Thị Hồng",
    dateOfBirth: "1978-12-08",
    address: "Khu Trung",
  },
  {
    id: "person-bich",
    saintName: "Anna",
    realName: "Lý Thị Bích",
    dateOfBirth: "1984-07-22",
    address: "Khu Nam",
  },
  {
    id: "person-sen",
    saintName: "Têrêsa",
    realName: "Võ Thị Sen",
    dateOfBirth: "1972-10-15",
    address: "Khu Tây",
  },
  {
    id: "person-xuan",
    saintName: "Maria",
    realName: "Nguyễn Thị Xuân",
    dateOfBirth: "1975-08-05",
    address: "Khu Bắc",
  },
  {
    id: "person-loanhm",
    saintName: "Anna",
    realName: "Phạm Thị Loan",
    dateOfBirth: "1981-03-25",
    address: "Khu Đông",
  },
  {
    id: "person-van",
    saintName: "Têrêsa",
    realName: "Hoàng Thị Vân",
    dateOfBirth: "1989-11-16",
    address: "Khu Tây",
  },
  {
    id: "person-hanhhm",
    saintName: "Cecilia",
    realName: "Đỗ Thị Hạnh",
    dateOfBirth: "1993-01-20",
    address: "Khu Nam",
  },
];

export function getMemberPersonById(personId: string): MemberPerson | undefined {
  return mockMemberPersons.find((p) => p.id === personId);
}
