import type { MemberServiceRecord } from "@/lib/organization/types";

export const mockMemberServiceRecords: MemberServiceRecord[] = [
  // person-son — Ca đoàn liên tục từ 2014 (≥10 năm, gộp “2014 – nay”)
  {
    id: "svc-son-ca-14",
    personId: "person-son",
    organizationSlug: "ca-doan",
    termId: "2014-2017",
    position: "Ca viên Tenor",
    status: "active",
  },
  {
    id: "svc-son-ca-17",
    personId: "person-son",
    organizationSlug: "ca-doan",
    termId: "2017-2020",
    position: "Ca viên Tenor",
    status: "active",
  },
  {
    id: "svc-son-ca-20",
    personId: "person-son",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Trưởng ca đoàn",
    status: "active",
  },
  {
    id: "svc-son-ca-23",
    personId: "person-son",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Trưởng ca đoàn",
    status: "active",
  },

  // person-hung — Ca đoàn + Legio
  {
    id: "svc-hung-ca-20",
    personId: "person-hung",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Phó trưởng ca đoàn",
    status: "active",
  },
  {
    id: "svc-hung-ca-23",
    personId: "person-hung",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Trưởng ca đoàn",
    status: "active",
  },
  {
    id: "svc-hung-lm-20",
    personId: "person-hung",
    organizationSlug: "legio-mariae",
    termId: "2020-2023",
    position: "Thành viên",
    status: "retired",
  },

  // person-anh — Ban Giáo lý + Ca đoàn
  {
    id: "svc-anh-gl-20",
    personId: "person-anh",
    organizationSlug: "ban-giao-ly",
    termId: "2020-2023",
    position: "Giáo lý viên Thiếu niên",
    status: "active",
  },
  {
    id: "svc-anh-gl-23",
    personId: "person-anh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Trưởng ban",
    status: "active",
  },
  {
    id: "svc-anh-ca-20",
    personId: "person-anh",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Ca viên Bass",
    status: "active",
  },

  // person-phucduc — đã về hưu
  {
    id: "svc-phucduc-gl-20",
    personId: "person-phucduc",
    organizationSlug: "ban-giao-ly",
    termId: "2020-2023",
    position: "Trưởng ban",
    status: "retired",
  },

  // Roster hiện tại (khóa 2023–2026 / 2020–2023)
  {
    id: "svc-hoa-ca-23",
    personId: "person-hoa",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Phó trưởng ca đoàn",
    status: "active",
  },
  {
    id: "svc-nam-ca-23",
    personId: "person-nam",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Thư ký",
    status: "active",
  },
  {
    id: "svc-mai-ca-23",
    personId: "person-mai",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Soprano",
    status: "active",
  },
  {
    id: "svc-duc-ca-23",
    personId: "person-duc",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Tenor",
    status: "active",
  },
  {
    id: "svc-tuan-ca-23",
    personId: "person-tuan",
    organizationSlug: "ca-doan",
    termId: "2023-2026",
    position: "Ca viên Bass",
    status: "active",
  },
  {
    id: "svc-lan-ca-20",
    personId: "person-lan",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Phó trưởng ca đoàn",
    status: "inactive",
  },
  {
    id: "svc-ngoc-ca-20",
    personId: "person-ngoc",
    organizationSlug: "ca-doan",
    termId: "2020-2023",
    position: "Ca viên Alto",
    status: "active",
  },
  {
    id: "svc-huong-gl-23",
    personId: "person-huong",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Phó trưởng ban",
    status: "active",
  },
  {
    id: "svc-hanh-gl-23",
    personId: "person-hanh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Giáo lý viên Chiên Con",
    status: "active",
  },
  {
    id: "svc-binh-gl-23",
    personId: "person-binh",
    organizationSlug: "ban-giao-ly",
    termId: "2023-2026",
    position: "Giáo lý viên Thiếu niên",
    status: "active",
  },
  {
    id: "svc-loan-gl-20",
    personId: "person-loan",
    organizationSlug: "ban-giao-ly",
    termId: "2020-2023",
    position: "Giáo lý viên",
    status: "active",
  },
  {
    id: "svc-thanh-gd-23",
    personId: "person-thanh",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Chủ tịch",
    status: "active",
  },
  {
    id: "svc-nga-gd-23",
    personId: "person-nga",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Phó chủ tịch",
    status: "active",
  },
  {
    id: "svc-cuong-gd-23",
    personId: "person-cuong",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Thành viên Giáo họ Trị Tin",
    status: "active",
  },
  {
    id: "svc-thu-gd-23",
    personId: "person-thu",
    organizationSlug: "gia-dinh-phuc-tu",
    termId: "2023-2026",
    position: "Thành viên Giáo họ Kim Lâm",
    status: "active",
  },
  {
    id: "svc-maingd-tn-23",
    personId: "person-maingd",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Tổng phụ trách",
    status: "active",
  },
  {
    id: "svc-huy-tn-23",
    personId: "person-huy",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Phó phụ trách",
    status: "active",
  },
  {
    id: "svc-khoi-tn-23",
    personId: "person-khoi",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Huynh trưởng",
    status: "active",
  },
  {
    id: "svc-an-tn-23",
    personId: "person-an",
    organizationSlug: "thieu-nhi-thanh-the",
    termId: "2023-2026",
    position: "Huynh trưởng",
    status: "active",
  },
  {
    id: "svc-hong-lm-23",
    personId: "person-hong",
    organizationSlug: "legio-mariae",
    termId: "2023-2026",
    position: "Tổng phụ trách",
    status: "active",
  },
  {
    id: "svc-bich-lm-23",
    personId: "person-bich",
    organizationSlug: "legio-mariae",
    termId: "2023-2026",
    position: "Thành viên",
    status: "active",
  },
  {
    id: "svc-sen-lm-20",
    personId: "person-sen",
    organizationSlug: "legio-mariae",
    termId: "2020-2023",
    position: "Tổng phụ trách",
    status: "retired",
  },
  {
    id: "svc-xuan-hm-23",
    personId: "person-xuan",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Chủ tịch",
    status: "active",
  },
  {
    id: "svc-loanhm-hm-23",
    personId: "person-loanhm",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Phó chủ tịch",
    status: "active",
  },
  {
    id: "svc-van-hm-23",
    personId: "person-van",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Thành viên",
    status: "active",
  },
  {
    id: "svc-hanhhm-hm-23",
    personId: "person-hanhhm",
    organizationSlug: "hiep-hoi-ba-me",
    termId: "2023-2026",
    position: "Thành viên",
    status: "active",
  },
];

export function getServiceRecordsByPersonId(
  personId: string,
): MemberServiceRecord[] {
  return mockMemberServiceRecords.filter((r) => r.personId === personId);
}
