import type { Person } from "./types";

const now = "2026-01-01T00:00:00+07:00";

export const mockPersons: Person[] = [
  {
    id: "p-001",
    saintName: "Phêrô",
    fullName: "Nguyễn Văn An",
    dateOfBirth: "1975-03-15",
    dateOfDeath: null,
    profileImage: null,
    gender: "male",
    status: "active",
    maritalStatus: "married",
    giaoHo: "Giáo họ Nhà Xứ",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "1975-04-20", church: "Nhà thờ Sa Nam" },
      firstCommunion: { date: "1985-06-01", church: "Nhà thờ Sa Nam" },
      confirmation: { date: "1990-05-10", church: "Nhà thờ Sa Nam" },
      marriage: { date: "2000-11-25", church: "Nhà thờ Sa Nam" },
    },
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    id: "p-002",
    saintName: "Maria",
    fullName: "Trần Thị Bình",
    dateOfBirth: "1978-07-22",
    dateOfDeath: null,
    profileImage: null,
    gender: "female",
    status: "active",
    maritalStatus: "married",
    giaoHo: "Giáo họ Nhà Xứ",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "1978-08-15", church: "Nhà thờ Sa Nam" },
      firstCommunion: { date: "1988-06-01", church: "Nhà thờ Sa Nam" },
      confirmation: { date: "1993-05-15", church: "Nhà thờ Sa Nam" },
      marriage: { date: "2000-11-25", church: "Nhà thờ Sa Nam" },
    },
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    id: "p-003",
    saintName: "Gioan",
    fullName: "Nguyễn Văn Cường",
    dateOfBirth: "2001-01-10",
    dateOfDeath: null,
    profileImage: null,
    gender: "male",
    status: "active",
    maritalStatus: "married",
    giaoHo: "Giáo họ Nhà Xứ",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "2001-02-14", church: "Nhà thờ Sa Nam" },
      firstCommunion: { date: "2011-06-01", church: "Nhà thờ Sa Nam" },
      confirmation: { date: "2016-05-20", church: "Nhà thờ Sa Nam" },
      marriage: { date: "2025-06-15", church: "Nhà thờ Sa Nam" },
    },
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    id: "p-004",
    saintName: "Teresa",
    fullName: "Nguyễn Thị Dung",
    dateOfBirth: "2003-09-05",
    dateOfDeath: null,
    profileImage: null,
    gender: "female",
    status: "away",
    maritalStatus: "single",
    giaoHo: "Giáo họ Nhà Xứ",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "2003-10-01", church: "Nhà thờ Sa Nam" },
      firstCommunion: { date: "2013-06-01", church: "Nhà thờ Sa Nam" },
      confirmation: { date: "2018-05-20", church: "Nhà thờ Sa Nam" },
      marriage: null,
    },
    createdAt: now,
    updatedAt: now,
    notes: "Đang học đại học tại Hà Nội",
  },
  {
    id: "p-005",
    saintName: "Anna",
    fullName: "Lê Thị Em",
    dateOfBirth: "2002-12-20",
    dateOfDeath: null,
    profileImage: null,
    gender: "female",
    status: "active",
    maritalStatus: "married",
    giaoHo: "Giáo họ Đồng Lạng",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "2003-01-10", church: "Nhà thờ Sa Nam" },
      firstCommunion: { date: "2012-06-01", church: "Nhà thờ Sa Nam" },
      confirmation: { date: "2017-05-20", church: "Nhà thờ Sa Nam" },
      marriage: { date: "2025-06-15", church: "Nhà thờ Sa Nam" },
    },
    createdAt: now,
    updatedAt: now,
    notes: null,
  },
  {
    id: "p-006",
    saintName: null,
    fullName: "Nguyễn Văn Phúc",
    dateOfBirth: "2026-02-10",
    dateOfDeath: null,
    profileImage: null,
    gender: "male",
    status: "active",
    maritalStatus: "single",
    giaoHo: "Giáo họ Nhà Xứ",
    giaoXu: "Sa Nam",
    giaoPhan: "Bùi Chu",
    sacraments: {
      baptism: { date: "2026-03-15", church: "Nhà thờ Sa Nam" },
      firstCommunion: null,
      confirmation: null,
      marriage: null,
    },
    createdAt: now,
    updatedAt: now,
    notes: "",
  },
];

export function getPersonById(id: string): Person | undefined {
  return mockPersons.find((p) => p.id === id);
}

export function searchPersons(query: string): Person[] {
  const q = query.toLowerCase();
  return mockPersons.filter(
    (p) =>
      p.fullName.toLowerCase().includes(q) ||
      (p.saintName?.toLowerCase().includes(q) ?? false),
  );
}
